# Generated by Django 3.1 on 2021-06-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210630_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AP', 'Arunachal Pradesh'), ('A', 'Assam'), ('B', 'Bihar'), ('CH', 'Chhattisgarh'), ('G', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jharkhand'), ('K', 'Karnataka'), ('K', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('IN', 'Manipur'), ('IA', 'Meghalaya'), ('KS', 'Mizoram'), ('KY', 'Nagaland'), ('LA', 'Odisha'), ('ME', 'Punjab'), ('RJ', 'Rajasthan'), ('UP', 'Uttar Pradesh')], max_length=100),
        ),
    ]
